version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - spring-boot-network

networks:
  spring-boot-network:
    driver: bridge
